project:
  type: website
  output-dir: docs

website:
  title: GREGonBoard
  navbar:
    background: primary
    search: true
    left:
    - text: Home
      href: index.qmd
  sidebar:
    style: docked
    search: true
    contents:
    - index.qmd
    - section: Foundations
      contents:
      - chapters/OHDSI.qmd
      - chapters/OMOPCDM.qmd
      - chapters/WhyGREG.qmd
    - section: Planning a study
      contents:
      - chapters/study_outline.qmd
      - chapters/study_protocol.qmd
    - section: Feasibility assessment
      contents:
      - chapters/standard_procedure.qmd
    - section: Design & Execution
      contents:
      - chapters/atlas.qmd
      - chapters/using_R.qmd
      - chapters/phenotyping.qmd
      - chapters/codelistgenerator.qmd
      - chapters/cohortconstruction.qmd
      - chapters/diagnostics.qmd
      - chapters/incidenceprevalence.qmd
      - chapters/characterisation.qmd
      - chapters/drugutilisation.qmd
      - chapters/effectiveness.qmd
    - section: Reporting a study
      contents: 
      - chapters/study_report.qmd
format:
  html:
    theme:
      light: [united, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-fold: show
    smooth-scroll: true
    css: include/webex.css
    include-after-body: include/webex.js
    
bibliography: references.bib
csl: american-medical-association-10th-edition.csl
editor: visual
