---
title: "GREGonBoard"
format: html
---

# Welcome

Whether you are a passionate stakeholder, data scientist, clinician, epidemiologist, patient or regulator, we welcome you on board to the GREG project! The GREG project creates, tests, and shares practical, evidence-based guidance and tools to help generate and use Real-World Evidence (RWE). By improving how RWE informs the development and evaluation of medicines, medical devices, and drug-device combinations, GREG supports better decision-making for regulators and Health Technology Assessment (HTA) bodies.

Every one has their role on GREG. In this tutorial, we will go through the main steps from study planning to study execution and report. Each section will have a brief summary of what will be explained on it. Feel free to only go through those lessons that are relevant for your work!

## Course structure

::: {.callout-note icon="false"}
## 1. Foundations

- [The OHDSI journey](chapters/OHDSI.qmd)
- [The OMOP CDM](chapters/OMOPCDM.qmd)
- [Why do we need GREG?](chapters/WhyGREG.qmd)
:::

::: {.callout-note icon="false"}
## 2. Study planning

- [Design of a study outline](chapters/study_outline.qmd) (with template)
- [Design of a study protocol](chapters/study_protocol.qmd) (with template)
:::

::: {.callout-note icon="false"}
## 3. Feasibility assessment

- [Standard procedure](chapters/standard_procedure.qmd)
:::

::: {.callout-note icon="false"}
## 4. Study design & execution

- [The webtool ATLAS](chapters/atlas.qmd)
- [CDM using R](chapters/using_R.qmd)
- [Phenotyping](chapters/phenotyping.qmd)
- [Codelists generation](chapters/codelistgenerator.qmd)
- [Cohort construction](chapters/cohortconstruction.qmd)
- [Diagnostic tools](chapters/diagnostics.qmd)
- [Incidence & prevalence study](chapters/incidenceprevalence.qmd)
- [Characterisation study](chapters/characterisation.qmd)
- [Drug utilisation study](chapters/drugutilisation.qmd)
- [Effectiveness study](chapters/effectiveness.qmd)
:::

::: {.callout-note icon="false"}
## 5. Study reporting

- [How to write a study report](chapters/study_report.qmd) (with template)
:::

## What to expect?

You will find a combination of theory, bibliographic/webographic sources, some examples, including R snippets, and short exercises.

::: callout-note
A single study is followed throughout the course: "Use of GLP-1 receptor agonists and risk of acute pancreatitis in type 2 diabetes patients"
:::

## Getting started

Navigate using the sidebar. You can change from light to dark mode using the top right button next to the search bar. You will be able to copy code snippets, and for interactive exercises, to edit and execute code online. Please, refrain from using AI to solve the exercises. Relevant sources will be available to do the exercises.

## Contact information

May you have any suggestions, doubts or inquiries please refer to:

> **Aida Perramon Malavez**
>
> a.perramonmalavez\@erasmusmc.nl
>
> Postdoctoral Researcher and GREGonBoard developer
