---
title: "OHDSI Journey"
format: html
---

## About OHDSI

The Observational Health Data Sciences and Informatics (or OHDSI, pronounced "Odyssey") program is a multi-stakeholder, interdisciplinary collaborative to bring out the value of health data through large-scale analytics. OHDSI has established an international network of researchers and observational health databases with a central coordinating center housed at Columbia University.

The OHDSI mission is to improve health by empowering a community to collaboratively generate the evidence that promotes better health decisions and better care. In OHDSI, and also in GREG (see [Why GREG?](WhyGREG.qmd)), we do large scale, multicentre analyses in a federated manner, so that data remains with each data partner and the only thing that is shared is the data format, the Observational Medical Outcomes Partnership (OMOP) Common Data Model (CDM), as well as analytical tools developed by the OHDSI collaborators and, most recently, by the [DARWIN EU®](https://www.darwin-eu.org/) project.

The OHDSI network was built to do [collaborative studies](https://data.ohdsi.org/OhdsiStudies/) to which one can adhere whether they find them interesting or recognise their potential contribution benefits. The [OHDSI forums](https://forums.ohdsi.org/) are the standard communication and informative tool, and you can find several nodes of OHDSI to "restrict" your research geographically, for example:

- OHDSI Europe

- OHDSI Japan

- OHDSI Korea

- OHDSI China

- OHDSI LATAM

- OHDSI en Español

But you can also find groups by role (developer, implementer, researcher...) and, of course, a *General* channel. There are regular meetings to which you are kindly requested to attend, may you have an ongoing project within the OHDSI network.

Read more about OHDSI: <https://www.ohdsi.org/>

## The Book of OHDSI

You can access the book of OHDSI here: <https://ohdsi.github.io/TheBookOfOhdsi/>

The OHDSI community wrote the book to serve as a central knowledge repository for all things OHDSI. This book is a great introduction to the OMOP CDM and how to plan and execute studies using OMOP CDM databases and OHDSI tools such as ATLAS or the OHDSI R packages.
